'use strict';

/**
 * Kovix MVP — Staging & Backup Engine ("Approve-Before-Write Gate")
 *
 * THE FOUNDATION OF THE COMPANY.
 *
 * Every file write generated by the autonomous agent — whether from the
 * 5-step Execute stage (main.js) or the chat-mode `write_file` tool
 * (tools.js) — MUST pass through this module. The proposed change is
 * queued, the renderer is notified via IPC, and the calling code awaits
 * user resolution BEFORE the file touches disk.
 *
 * Resolution actions:
 *   - 'accept'  → write the proposed content as-is, backup original first
 *   - 'modify'  → write user-edited content (Monaco inline edit), backup first
 *   - 'reject'  → do NOT write; return the user's reason to the agent for retry
 *
 * Auto-modes (escape hatches for power users — "Accept All" / "Reject All"):
 *   - 'manual'      (default) require explicit user action per file
 *   - 'accept-all'  auto-accept all future proposals in this run
 *   - 'reject-all'  auto-reject all future proposals in this run
 *
 * Backup policy:
 *   Before any accepted/modified write that OVERWRITES an existing file,
 *   the original is copied to `.kovix/backups/<relpath>.<ISO>.bak`.
 *   New files (no prior version) are not backed up (nothing to back up).
 *   `.kovix/` is already in main.js IGNORED_DIRS so backups never clutter
 *   the file tree.
 *
 * Architecture: this module is a SINGLETON. `main.js` calls `staging.init()`
 * on app ready with a workspace getter and a sendToRenderer function.
 * `tools.js` imports the singleton and calls `staging.propose()` from the
 * `write_file` tool. The Execute step in `main.js` does the same.
 *
 * Thread-safety: Node is single-threaded, so the singleton is safe. The
 * pendingResolve field holds at most one Promise resolver at a time —
 * proposals are processed strictly sequentially.
 */

const fs = require('fs');
const fsp = require('fs').promises;
const path = require('path');
const crypto = require('crypto');

/* -------------------------------------------------------------------------- */
/* Constants                                                                  */
/* -------------------------------------------------------------------------- */

const BACKUPS_DIRNAME = '.kovix';
const BACKUPS_SUBDIR = 'backups';

// IPC channels — main → renderer
const STAGING_CHANNELS = {
  PROPOSE: 'staging:propose',           // a new proposal is awaiting user action
  QUEUE_UPDATE: 'staging:queue-update', // the queue state changed
};

// Valid auto-mode values
const AUTO_MODES = ['manual', 'accept-all', 'reject-all'];

// Max file size we'll read for diffing (8 MB) — same as MAX_READ_BYTES in main.js
const MAX_DIFF_BYTES = 8 * 1024 * 1024;

/* -------------------------------------------------------------------------- */
/* StagingManager                                                             */
/* -------------------------------------------------------------------------- */

class StagingManager {
  constructor() {
    this._initialized = false;
    this._getWorkspace = null;       // () => Promise<string> | string
    this._sendToRenderer = null;     // (channel, payload) => void
    this._queue = [];                // Array<Proposal>
    this._currentIndex = 0;          // index of the proposal currently awaiting resolution
    this._pendingResolve = null;     // { resolve } for the current proposal's Promise
    this._autoMode = 'manual';       // 'manual' | 'accept-all' | 'reject-all'
    this._autoRejectReason = '';     // reason fed back to agent when auto-rejecting
  }

  /* ------------------------------------------------------------------------ */
  /* Initialization                                                           */
  /* ------------------------------------------------------------------------ */

  /**
   * Initialize the staging manager. Called once on app ready from main.js.
   *
   * @param {{
   *   getWorkspace: () => (Promise<string> | string),
   *   sendToRenderer: (channel: string, payload: any) => void,
   * }} opts
   */
  init({ getWorkspace, sendToRenderer }) {
    if (typeof getWorkspace !== 'function') {
      throw new Error('staging.init: getWorkspace must be a function');
    }
    if (typeof sendToRenderer !== 'function') {
      throw new Error('staging.init: sendToRenderer must be a function');
    }
    this._getWorkspace = getWorkspace;
    this._sendToRenderer = sendToRenderer;
    this._initialized = true;
    console.log('[staging] initialized');
  }

  /**
   * Returns true if init() has been called. Used by tools.js to decide
   * whether to route write_file through staging or fall back to a direct
   * write (for standalone tests where staging was never initialized).
   */
  isInitialized() {
    return this._initialized === true;
  }

  /* ------------------------------------------------------------------------ */
  /* Public: propose a write                                                  */
  /* ------------------------------------------------------------------------ */

  /**
   * Propose a file write. The calling agent code AWAITS this; it resolves
   * only after the user (or auto-mode) decides what to do.
   *
   * @param {string} relPath - workspace-relative path (or absolute, will be resolved)
   * @param {string} newContent - proposed new file content
   * @param {string} source - 'execute' | 'write_file' | string identifying caller
   * @returns {Promise<{action: 'accept'|'modify'|'reject', finalContent: string, reason?: string}>}
   */
  async propose(relPath, newContent, source) {
    if (!this._initialized) {
      throw new Error('StagingManager not initialized. Call init() first.');
    }
    if (typeof newContent !== 'string') {
      throw new Error('staging.propose: newContent must be a string');
    }

    const workspace = await Promise.resolve(this._getWorkspace());
    if (!workspace) {
      throw new Error('No active workspace. Cannot stage writes without a workspace.');
    }

    // Resolve to absolute path
    const absPath = path.isAbsolute(relPath)
      ? relPath
      : path.resolve(workspace, relPath);

    // Sanity: file must live INSIDE the workspace (security)
    const wsResolved = path.resolve(workspace);
    if (absPath !== wsResolved && !absPath.startsWith(wsResolved + path.sep)) {
      throw new Error(`Staged write is OUTSIDE the workspace: ${relPath}`);
    }

    // Read existing content (if any) for the diff
    let oldContent = null;
    let oldSize = 0;
    try {
      const stat = await fsp.stat(absPath);
      if (stat.isFile()) {
        oldSize = stat.size;
        if (stat.size <= MAX_DIFF_BYTES) {
          oldContent = await fsp.readFile(absPath, 'utf8');
        } else {
          // File too large to diff — show a placeholder. The user can still
          // accept (overwrite) but won't see a useful diff.
          oldContent = `<file too large to diff: ${stat.size} bytes>`;
        }
      }
    } catch (_) {
      // file doesn't exist — this is a CREATE, not a MODIFY
    }

    const relPathNorm = path.relative(workspace, absPath);
    const proposal = {
      id: crypto.randomUUID(),
      path: relPathNorm,
      absPath,
      oldContent,
      newContent,
      source: source || 'unknown',
      isCreate: oldContent === null,
      oldSize,
      status: 'pending',          // 'pending' | 'resolved:accept' | 'resolved:modify' | 'resolved:reject' | 'resolved:auto-accept' | 'resolved:auto-reject' | 'error'
      createdAt: new Date().toISOString(),
      resolvedAt: null,
      error: null,
    };

    this._queue.push(proposal);

    // ---- Auto-mode short-circuit ----
    // If the user previously clicked "Accept All" or "Reject All", resolve
    // this proposal immediately without involving the renderer.
    if (this._autoMode === 'accept-all') {
      const finalContent = newContent;
      try {
        await this._writeWithBackup(absPath, finalContent, workspace);
        proposal.status = 'resolved:auto-accept';
        proposal.resolvedAt = new Date().toISOString();
      } catch (err) {
        proposal.status = 'error';
        proposal.error = err.message;
        this._broadcastQueue();
        throw err;
      }
      this._broadcastQueue();
      return { action: 'accept', finalContent };
    }

    if (this._autoMode === 'reject-all') {
      const reason = this._autoRejectReason || 'User rejected all remaining changes';
      proposal.status = 'resolved:auto-reject';
      proposal.resolvedAt = new Date().toISOString();
      this._broadcastQueue();
      return { action: 'reject', finalContent: newContent, reason };
    }

    // ---- Manual mode: notify renderer and wait ----
    this._broadcastQueue();
    this._sendToRenderer(STAGING_CHANNELS.PROPOSE, {
      proposal: this._serializeProposal(proposal),
    });

    return new Promise((resolve) => {
      this._pendingResolve = resolve;
    });
  }

  /* ------------------------------------------------------------------------ */
  /* Public: resolve the pending proposal                                     */
  /* ------------------------------------------------------------------------ */

  /**
   * Resolve the current pending proposal. Called by IPC when the user
   * clicks Accept / Reject / Modify in the renderer.
   *
   * @param {{action: 'accept'|'reject'|'modify', finalContent?: string, reason?: string}} decision
   * @returns {Promise<{ok: boolean, result?: object, error?: string}>}
   */
  async resolve(decision) {
    if (!this._initialized) {
      return { ok: false, error: 'StagingManager not initialized.' };
    }
    if (!this._pendingResolve) {
      return { ok: false, error: 'No pending proposal to resolve.' };
    }
    if (!decision || typeof decision !== 'object') {
      return { ok: false, error: 'Invalid decision payload.' };
    }

    const { action, finalContent, reason } = decision;
    if (!['accept', 'reject', 'modify'].includes(action)) {
      return { ok: false, error: `Unknown action: ${action}` };
    }

    const current = this._queue[this._currentIndex];
    if (!current) {
      return { ok: false, error: 'No current proposal in queue.' };
    }

    const workspace = await Promise.resolve(this._getWorkspace());
    if (!workspace) {
      return { ok: false, error: 'No active workspace.' };
    }

    let result;

    if (action === 'accept') {
      const content = current.newContent;
      try {
        await this._writeWithBackup(current.absPath, content, workspace);
        current.status = 'resolved:accept';
        result = { action: 'accept', finalContent: content };
      } catch (err) {
        current.status = 'error';
        current.error = err.message;
        this._broadcastQueue();
        this._advanceAndResolve({
          action: 'reject',
          finalContent: content,
          reason: `Write failed: ${err.message}`,
        });
        return { ok: false, error: err.message };
      }
    } else if (action === 'modify') {
      if (typeof finalContent !== 'string') {
        return { ok: false, error: 'Modified content is required for action=modify.' };
      }
      try {
        await this._writeWithBackup(current.absPath, finalContent, workspace);
        current.newContent = finalContent;
        current.status = 'resolved:modify';
        result = { action: 'modify', finalContent };
      } catch (err) {
        current.status = 'error';
        current.error = err.message;
        this._broadcastQueue();
        this._advanceAndResolve({
          action: 'reject',
          finalContent,
          reason: `Write failed: ${err.message}`,
        });
        return { ok: false, error: err.message };
      }
    } else if (action === 'reject') {
      current.status = 'resolved:reject';
      result = {
        action: 'reject',
        finalContent: current.newContent,
        reason: reason || 'User rejected the change',
      };
    }

    current.resolvedAt = new Date().toISOString();
    this._advanceAndResolve(result);
    this._broadcastQueue();
    return { ok: true, result };
  }

  /* ------------------------------------------------------------------------ */
  /* Public: auto-mode (Accept All / Reject All)                              */
  /* ------------------------------------------------------------------------ */

  /**
   * Set the auto-mode for the current run.
   * @param {'manual'|'accept-all'|'reject-all'} mode
   * @param {string} [reason=''] - reason for reject-all (fed back to agent)
   */
  setAutoMode(mode, reason = '') {
    if (!AUTO_MODES.includes(mode)) {
      throw new Error(`Unknown auto-mode: ${mode}`);
    }
    this._autoMode = mode;
    this._autoRejectReason = reason || '';
    this._broadcastQueue();

    // If switching to auto-mode AND there's a pending proposal, resolve it now
    // (the user clicked "Accept All" or "Reject All" while a diff was on screen)
    if (this._pendingResolve && mode !== 'manual') {
      const current = this._queue[this._currentIndex];
      if (current) {
        if (mode === 'accept-all') {
          // Fire-and-forget — the resolver will advance the queue
          this.resolve({ action: 'accept' }).catch((err) => {
            console.error('[staging] auto-accept failed:', err);
          });
        } else if (mode === 'reject-all') {
          this.resolve({ action: 'reject', reason }).catch((err) => {
            console.error('[staging] auto-reject failed:', err);
          });
        }
      }
    }
  }

  /**
   * Reset auto-mode back to 'manual' (e.g. when starting a new run).
   */
  clearAutoMode() {
    this._autoMode = 'manual';
    this._autoRejectReason = '';
    this._broadcastQueue();
  }

  /* ------------------------------------------------------------------------ */
  /* Public: getters                                                          */
  /* ------------------------------------------------------------------------ */

  /**
   * Get the current pending proposal (or null).
   * Returns a sanitized copy safe to send to the renderer.
   */
  getCurrent() {
    const current = this._queue[this._currentIndex];
    if (!current || current.status !== 'pending') return null;
    return this._serializeProposal(current);
  }

  /**
   * Get a summary of the entire queue state.
   */
  getQueue() {
    return {
      queue: this._queue.map((p) => this._serializeProposalSummary(p)),
      currentIndex: this._currentIndex,
      autoMode: this._autoMode,
      autoRejectReason: this._autoRejectReason,
      pendingCount: this._queue.slice(this._currentIndex).filter((p) => p.status === 'pending').length,
      resolvedCount: this._queue.filter((p) => p.status.startsWith('resolved:')).length,
      errorCount: this._queue.filter((p) => p.status === 'error').length,
    };
  }

  /* ------------------------------------------------------------------------ */
  /* Public: reset (called on workspace switch / new session / mode switch)   */
  /* ------------------------------------------------------------------------ */

  /**
   * Reset the staging state. Any pending proposal is resolved with
   * action='reject' so the agent loop doesn't hang forever.
   *
   * Called by main.js on:
   *  - Workspace switch (dialog:open-folder)
   *  - New session (sessions:new)
   *  - Session load (sessions:load)
   *  - Mode switch (agent ↔ chat)
   */
  reset() {
    if (this._pendingResolve) {
      this._advanceAndResolve({
        action: 'reject',
        finalContent: '',
        reason: 'Staging was reset (workspace or session changed).',
      });
    }
    this._queue = [];
    this._currentIndex = 0;
    this._autoMode = 'manual';
    this._autoRejectReason = '';
    this._broadcastQueue();
    console.log('[staging] reset');
  }

  /* ------------------------------------------------------------------------ */
  /* Private: write with backup                                               */
  /* ------------------------------------------------------------------------ */

  /**
   * Write content to a file, backing up the existing version first if any.
   *
   * Backup path: `<workspace>/.kovix/backups/<relpath-with-seps-as-__>.<ISO-timestamp>.bak`
   *
   * @param {string} absPath - absolute file path to write
   * @param {string} content - new content
   * @param {string} workspace - absolute workspace root
   * @private
   */
  async _writeWithBackup(absPath, content, workspace) {
    // Ensure .kovix/backups/ exists (recursive — .kovix/ may not exist yet)
    const backupsDir = path.join(workspace, BACKUPS_DIRNAME, BACKUPS_SUBDIR);
    await fsp.mkdir(backupsDir, { recursive: true });

    // Backup the existing file IF it exists
    try {
      await fsp.access(absPath);
      const stat = await fsp.stat(absPath);
      if (stat.isFile()) {
        const relPath = path.relative(workspace, absPath);
        // Sanitize path for backup filename: replace separators with __ so
        // "src/components/Button.tsx" becomes "src__components__Button.tsx"
        const safeName = relPath.replace(/[\\/]/g, '__');
        const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
        const backupPath = path.join(backupsDir, `${safeName}.${timestamp}.bak`);
        await fsp.copyFile(absPath, backupPath);
        console.log(
          `[staging] backed up ${relPath} → ${path.relative(workspace, backupPath)}`
        );
      }
    } catch (_) {
      // file doesn't exist — nothing to back up, that's fine
    }

    // Ensure parent directory of target file exists (e.g. for "src/foo/bar.js")
    await fsp.mkdir(path.dirname(absPath), { recursive: true });

    // Write the new content
    await fsp.writeFile(absPath, content, 'utf8');
    console.log(
      `[staging] wrote ${content.length} chars to ${path.relative(workspace, absPath)}`
    );
  }

  /* ------------------------------------------------------------------------ */
  /* Private: queue advancement                                               */
  /* ------------------------------------------------------------------------ */

  /**
   * Resolve the current pending Promise and advance the index.
   * @param {object} result - the value to resolve the pending Promise with
   * @private
   */
  _advanceAndResolve(result) {
    const resolveFn = this._pendingResolve;
    this._pendingResolve = null;
    this._currentIndex++;
    if (typeof resolveFn === 'function') {
      resolveFn(result);
    }
  }

  /* ------------------------------------------------------------------------ */
  /* Private: serialization                                                   */
  /* ------------------------------------------------------------------------ */

  /**
   * Full proposal object — sent to the renderer when a proposal is first
   * staged (so the renderer can render the diff). Includes oldContent and
   * newContent.
   * @private
   */
  _serializeProposal(p) {
    return {
      id: p.id,
      path: p.path,
      absPath: p.absPath,
      oldContent: p.oldContent,
      newContent: p.newContent,
      source: p.source,
      isCreate: p.isCreate,
      oldSize: p.oldSize,
      status: p.status,
      createdAt: p.createdAt,
      resolvedAt: p.resolvedAt,
      error: p.error || null,
    };
  }

  /**
   * Lightweight summary — used for the queue state broadcast (no content).
   * @private
   */
  _serializeProposalSummary(p) {
    return {
      id: p.id,
      path: p.path,
      source: p.source,
      isCreate: p.isCreate,
      status: p.status,
      createdAt: p.createdAt,
      resolvedAt: p.resolvedAt,
      error: p.error || null,
    };
  }

  /**
   * Broadcast the current queue state to the renderer.
   * @private
   */
  _broadcastQueue() {
    if (this._sendToRenderer) {
      this._sendToRenderer(STAGING_CHANNELS.QUEUE_UPDATE, this.getQueue());
    }
  }
}

/* -------------------------------------------------------------------------- */
/* Singleton                                                                  */
/* -------------------------------------------------------------------------- */

const staging = new StagingManager();

module.exports = {
  staging,
  StagingManager,
  STAGING_CHANNELS,
  AUTO_MODES,
  BACKUPS_DIRNAME,
  BACKUPS_SUBDIR,
};
